services:

  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres-db

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql

    networks:
      - app-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network


  # Microservices
  event-api:
    ports:
      - "8084:8084"
    build:
      context: .
      dockerfile: event-service/Dockerfile
    container_name: event-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  booking-api:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    container_name: booking-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      event-api:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/booking_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      EVENT_SERVICE_URL: http://event-api:8084
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: