services:

  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:8.1.1
    container_name: kafka-broker
    hostname: kafka
    restart: unless-stopped
    ports:
      - "127.0.0.1:9092:9092"
    networks:
      - app-network
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CLUSTER_ID: lcEE_0O5R_2ueRWWNGLdXg
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-init:
    image: confluentinc/cp-kafka:8.1.1
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    command:
      - bash
      - -ec
      - |
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tickethub.payment.events.v1 --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tickethub.payment.events.v1.dlt --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tickethub.booking.events.v1 --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tickethub.booking.events.v1.dlt --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tickethub.ticket.events.v1 --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tickethub.ticket.events.v1.dlt --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tickethub.events.changes.v1 --partitions 1 --replication-factor 1
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    container_name: keycloak
    command: start-dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak_db
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:8180:8080"
    networks:
      - app-network



  # Microservices
  event-api:
    build:
      context: .
      dockerfile: event-service/Dockerfile
    container_name: event-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_EVENTS_TOPIC: tickethub.events.changes.v1
      JAEGER_URL: http://jaeger:4318/v1/traces
      ELASTICSEARCH_URL: http://elasticsearch:9200

  ticket-api:
    build:
      context: .
      dockerfile: ticket-service/Dockerfile
    container_name: ticket-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticket_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_BOOKING_EVENTS_TOPIC: tickethub.booking.events.v1
      KAFKA_TICKET_EVENTS_TOPIC: tickethub.ticket.events.v1
      OUTBOX_RELAY_DELAY_MS: 1000
      JAEGER_URL: http://jaeger:4318/v1/traces

  booking-api:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    container_name: booking-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
      event-api:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/booking_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      EVENT_SERVICE_URL: http://event-api:8084
      PAYMENT_GRPC_HOST: payment-api
      PAYMENT_GRPC_PORT: 9090
      PAYMENT_GRPC_DEADLINE_SECONDS: 3
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_PAYMENT_EVENTS_TOPIC: tickethub.payment.events.v1
      KAFKA_BOOKING_EVENTS_TOPIC: tickethub.booking.events.v1
      OUTBOX_RELAY_FIXED_DELAY_MS: 2000
      OUTBOX_RELAY_BATCH_SIZE: 100
      KAFKA_TICKET_EVENTS_TOPIC: tickethub.ticket.events.v1
      KAFKA_TICKET_EVENTS_GROUP_ID: booking-ticket-events-v1
      JAEGER_URL: http://jaeger:4318/v1/traces
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      booking-api:
        condition: service_started
      ticket-api:
        condition: service_started
      event-api:
        condition: service_started
      keycloak:
        condition: service_started
    environment:
      BOOKING_SERVICE_URL: http://booking-api:8081
      TICKET_SERVICE_URL: http://ticket-api:8083
      EVENT_SERVICE_URL: http://event-api:8084
      KEYCLOAK_ISSUER_URI: http://localhost:8180/realms/tickethub
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/tickethub/protocol/openid-connect/certs
      JAEGER_URL: http://jaeger:4318/v1/traces
    ports:
      - "8080:8080"
    networks:
      - app-network

  payment-api:
    build:
      context: ./payment-service
      dockerfile: ./cmd/server/Dockerfile
    container_name: payment-api
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/payment_db?sslmode=disable
      HTTP_PORT: 8085
      GRPC_PORT: 9090
      MOCK_CHECKOUT_URL: http://localhost:8085/api/v1/mock/payments
      KAFKA_BROKERS: kafka:29092
      KAFKA_PAYMENT_EVENTS_TOPIC: tickethub.payment.events.v1
      KAFKA_BOOKING_EVENTS_TOPIC: tickethub.booking.events.v1
      KAFKA_BOOKING_EVENTS_GROUP_ID: payment-booking-events-v1
      KAFKA_BOOKING_EVENTS_DLT_TOPIC: tickethub.booking.events.v1.dlt
      OUTBOX_RELAY_INTERVAL: 2s
      OUTBOX_RELAY_BATCH_SIZE: 100
    ports:
      - "8085:8085"
      - "9090:9090"
    networks:
      - app-network


  # Observability
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - app-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - app-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network
    depends_on:
      - loki

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - app-network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - app-network
    depends_on:
      - elasticsearch

networks:
  app-network:

volumes:
  db_data:
  kafka_data:
  es_data:
