server:
  port: 8081

spring:
  application:
    name: booking-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/booking_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}


clients:
  event-service:
    url: ${EVENT_SERVICE_URL:http://event-api:8084}