server:
  port: 8084

spring:
  application:
    name: event-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/event_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${JAEGER_URL:http://jaeger:4318/v1/traces}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n"